POST http://localhost:5000/api/addresses
Content-Type: application/json

{
  "street": "Main Street",
  "house_number": "123",
  "house_number_extension": "A",
  "house_number_extension_extra": "Extra",
  "zipcode": "12345",
  "city": "Example City",
  "province": "Example Province",
  "country_code": "NL"
}
###
### Show Single Id Address
GET  http://localhost:5000/api/addresses/b372cf41-44f1-4823-a97c-316fef12ba27
###