# Create Client with Contact ID and Address ID
POST http://localhost:5000/api/clients
Content-Type: application/json

{
  "name": "Client D",
  "contact_id": "a2a2bb62-0398-4b76-a80e-0f509154906f",
  "address_id": "21903d3a-3d0f-4949-bf0d-e2a84cd1a450"
}
###
# Update Client with Contact ID and Address ID
PUT http://localhost:5000/api/clients/fa5946ab-2ab8-4274-a2eb-b717855f8dca
Content-Type: application/json

{
  "name": "Updated Client D",
  "contact_id": "8d2e7d61-e596-46e4-acd8-e85ef8805110",
  "address_id": "0ba16ba7-0c7a-45de-9fe6-9054fb6df6a8"
}
###
# Delete Clients
DELETE http://localhost:5000/api/clients/4a07f327-2ce1-499a-b2ab-692ce2a471be
###
### GetById Clients
GET http://localhost:5000/api/clients/17187ac9-34b3-4a94-b4c9-922c06606117
###
### GetAll Clients
GET http://localhost:5000/api/clients
###