# Create Client with Contact ID and Address ID
POST http://localhost:5000/api/clients
Content-Type: application/json

{
  "name": "Client D",
  "contact_id": "3f2488a2-7747-4541-b29a-a28735ebd921",
  "address_id": "016d60c2-a192-497a-b72c-49a1dedc3dab"
}
###
# Update Client with Contact ID and Address ID
PUT http://localhost:5000/api/clients/e6ee7b10-2dbf-4bcd-aeed-7071e3f76b9e
Content-Type: application/json

{
  "name": "Updated Client D",
  "contact_id": "3f2488a2-7747-4541-b29a-a28735ebd921",
  "address_id": "016d60c2-a192-497a-b72c-49a1dedc3dab"
}
###
# Delete Clients
DELETE http://localhost:5000/api/clients/e6ee7b10-2dbf-4bcd-aeed-7071e3f76b9e
###
### GetById Clients
GET http://localhost:5000/api/clients/17187ac9-34b3-4a94-b4c9-922c06606117
###
### GetAll Clients
GET http://localhost:5000/api/clients
###