## Create Contact
POST http://localhost:5000/api/contacts
Content-Type: application/json

{
    "name": "Jane Doe",
    "function": "Sales",
    "phone": "+123456789",
    "email": "john.doe@example.com"
}
###
## Update Contact
PUT http://localhost:5000/api/contacts/b2efa902-9f5c-4a27-84b3-fa3fdecf991b
Content-Type: application/json

{
    "name": "Jan Frans",
    "phone": "+977654321",
    "email": "jan.frans@example.com",
    "function": "CEO"
}
###
### Get all Contact
GET http://localhost:5000/api/contacts
###
### Get Contact by ID
GET http://localhost:5000/api/contacts/3a51b000-65da-47ee-88e6-42cd8908057e
###
### Delete Contact
DELETE http://localhost:5000/api/contacts/b2efa902-9f5c-4a27-84b3-fa3fdecf991b
###