## Create Contact
POST http://localhost:5000/api/contacts
Content-Type: application/json

{
    "name": "John Doe",
    "phone": "+123456789",
    "email": "john.doe@example.com"
}
###
## Update Contact
PUT http://localhost:5000/api/contacts/422d16fb-9a03-4998-8c97-ce0ea25fbd7a
Content-Type: application/json

{
    "name": "Jane Doe",
    "phone": "+977654321",
    "email": "jane.doe@example.com"
}
###
### Get all Contact
GET http://localhost:5000/api/contacts
###
### Get Contact by ID
GET http://localhost:5000/api/contacts/422d16fb-9a03-4998-8c97-ce0ea25fbd7a
###
### Delete Contact
DELETE http://localhost:5000/api/contacts/422d16fb-9a03-4998-8c97-ce0ea25fbd7a
###