## Create Contact
POST http://localhost:5000/api/contacts
Content-Type: application/json

{
    "name": "John Doe",
    "phone": "+123456789",
    "email": "john.doe@example.com"
}
###
## Update Contact
PUT http://localhost:5000/api/contacts/af5cc9d0-6b2e-4122-a2ef-dbf095892d88
Content-Type: application/json

{
    "name": "Jane Doe",
    "phone": "+977654321",
    "email": "jane.doe@example.com"
}
###
### Get all Contact
GET http://localhost:5000/api/contacts
###
### Get Contact by ID
GET http://localhost:5000/api/contacts/8d2e7d61-e596-46e4-acd8-e85ef8805110
###
### Delete Contact
DELETE http://localhost:5000/api/contacts/dceae1cc-a77c-4526-9ca8-3fb0b9030cc2
###