
POST http://localhost:5000/api/inventories
Content-Type: application/json

{
  "description": "INVENTORY ITEM 3 DESCRIPTION",
  "item_reference": "INVENTORY ITEM 3 REFERENCE",
  "item_id": "45a937f6-2724-40a4-8c9d-629f7c573ac9",
  "locations": [
    {
      "location_id": "646fd5c8-425e-44a9-9d5a-3d603e692092",
      "on_hand": 17
    }
  ]
}
###

PUT http://localhost:5000/api/inventories/39201c04-2adc-42f1-982a-b47852ec3e86
Content-Type: application/json

{
  "description": "The description",
  "item_reference": "Some item",
  "item_id": "45a937f6-2724-40a4-8c9d-629f7c573ac9",
  "locations": [
    {
      "location_id": "a38df692-09ed-418a-8c53-7ea765a895ce",
      "on_hand": 800
    }
    ,
    {
      "location_id": "afb7929f-5929-4574-a652-5ef7b830ede0",
      "on_hand": 800
    }
  ]
}
###

GET http://localhost:5000/api/inventories
Content-Type: application/json
###

GET http://localhost:5000/api/inventories/39201c04-2adc-42f1-982a-b47852ec3e86
Content-Type: application/json
###

DELETE http://localhost:5000/api/inventories/39201c04-2adc-42f1-982a-b47852ec3e86
Content-Type: application/json
###