### GET ITEM BY ID
GET http://localhost:5000/api/items/18063ce1-1726-4d2c-9de8-9f90673f0e66
Content-Type: application/json
###

### GET INVENTORIES BASED ON SPECIFIC ITEM ID
GET http://localhost:5000/api/items/d5c91d5f-3a91-4baf-8505-07401913b734/inventories
Content-Type: application/json
###

### GET INVENTORIES TOTALS BASED ON SPECIFIC ITEM ID 
GET http://localhost:5000/api/items/d5c91d5f-3a91-4baf-8505-07401913b734/inventories/totals
Content-Type: application/json
###

### GET ALL ITEM 
GET http://localhost:5000/api/items/
Content-Type: application/json
###

### CREATE ITEM
POST http://localhost:5000/api/items
Content-Type: application/json

{
  "code": "ITEM TEST 21",
  "description": "High-quality ergonomic office chair with adjustable height and back support",
  "short_description": "Ergonomic office chair",
  "upc_code": "123456789012",
  "model_number": "CH-ERG-XL",
  "commodity_code": "9401710000",
  "unit_purchase_quantity": -1,
  "unit_order_quantity": 1,
  "pack_order_quantity": 10,
  "supplier_reference_code": "123-ABCD",
  "supplier_part_number": "CH123-XL",
  "item_group_id": null,
  "item_line_id": null,
  "item_type_id": null,
  "supplier_id": "d337b2d9-655d-4ddb-b35b-de80c0c60520"
}
###

### UPDATE ITEM
PUT http://localhost:5000/api/items/18063ce1-1726-4d2c-9de8-9f90673f0e66
Content-Type: application/json

{
  "code": "X",
  "description": "High-quality ergonomic office chair with adjustable height and back support",
  "short_description": "Ergonomic office chair",
  "upc_code": "123456789012",
  "model_number": "CH-ERG-XL",
  "commodity_code": "9401710000",
  "unit_purchase_quantity": -1,
  "unit_order_quantity": 1,
  "pack_order_quantity": 1,
  "supplier_reference_code": "123-ABCD",
  "supplier_part_number": "CH123-XL",
  "supplier_id": "27a1e19b-32bf-4e14-a21e-12ef2bd919d2"
}
###

### DELETE ITEM
DELETE http://localhost:5000/api/items/8d95b66e-ecd0-4c57-a1ce-9ab4d4b9a07e
Content-Type: application/json

###