### CREATE ITEM LINE
POST http://localhost:5000/api/ItemLines
Content-Type: application/json

{
    "name" : "1",
    "description": "1"
}
###


### UPDATE ITEM LINE
PUT http://localhost:5000/api/ItemLines/d141e044-ce23-4d01-9c44-508b5c4f106d
Content-Type: application/json

{
    "name" : "1",
    "description": "1"
}
###

### DELETE ITEM LINE
DELETE http://localhost:5000/api/ItemLines/d141e044-ce23-4d01-9c44-508b5c4f106d
Content-Type: application/json
###

### GET ALL ITEM LINES
GET http://localhost:5000/api/itemlines
Content-Type: application/json
###

### GET ITEM LINE BY ID
GET http://localhost:5000/api/itemlines/d141e044-ce23-4d01-9c44-508b5c4f106d
Content-Type: application/json
###

### GET ALL ITEMS FROM ITEM LINES
GET http://localhost:5000/api/itemlines/d141e044-ce23-4d01-9c44-508b5c4f106d/items
Content-Type: application/json
###