### CREATE ITEM LINE
POST http://localhost:5000/api/ItemLines
Content-Type: application/json

{
    "name" : "1",
    "description": "1"
}
###


### UPDATE ITEM LINE
PUT http://localhost:5000/api/ItemLines/488d6d27-80d4-4187-968e-e28b468c1b14
Content-Type: application/json

{
    "name" : "1",
    "description": "1"
}
###

### DELETE ITEM LINE
DELETE http://localhost:5000/api/ItemLines/42bca5a7-1bda-48cb-8008-8884b4a208ab
Content-Type: application/json
###

### GET ALL ITEM LINES
GET http://localhost:5000/api/itemlines
Content-Type: application/json
###

### GET ITEM LINE BY ID
GET http://localhost:5000/api/itemlines/04ccd936-c43b-4568-aa5a-b23093c0b8d8
Content-Type: application/json
###

### GET ALL ITEMS FROM ITEM LINES
GET http://localhost:5000/api/itemlines/cf00599d-e7df-446b-abd7-46830459a864/items
Content-Type: application/json
###