### CREATE ITEM TYPE
POST http://localhost:5000/api/ItemTypes
Content-Type: application/json

{
    "name" : "1",
    "description": "1"
}
###

### UPDATE ITEM TYPE
PUT http://localhost:5000/api/ItemTypes/413586e0-4698-426d-9da1-93fef530c541
Content-Type: application/json

{
    "name" : "1",
    "description": "1"
}

### DELETE ITEM TYPE
DELETE http://localhost:5000/api/ItemTypes/413586e0-4698-426d-9da1-93fef530c541
Content-Type: application/json
###

### GET ITEM TYPE BY ID
GET http://localhost:5000/api/itemtypes/413586e0-4698-426d-9da1-93fef530c541
Content-Type: application/json
###

### GET ALL ITEM TYPES
GET http://localhost:5000/api/itemtypes
Content-Type: application/json
###

### GET ALL ITEMS FROM ITEM TYPES
GET http://localhost:5000/api/itemtypes/db359ddb-1d7c-415c-bd26-a7386f319d4b/items
Content-Type: application/json
###