### CREATE SHIPMENT
POST http://localhost:5000/api/shipments
Content-Type: application/json

{
  "order_id": "0415f598-6998-4340-8275-999dafb961e8",
  "order_date": "2023-11-19T14:12:33.807Z",
  "request_date": "2024-11-19T14:12:33.807Z",
  "shipment_date": "2024-11-19T14:12:33.807Z",
  "shipment_type": "I",
  "shipment_status": "Delivered",
  "notes": "geen notities",
  "carrier_code": "123",
  "carrier_description": "description",
  "service_code": "321",
  "payment_type": "Automatic",
  "transfer_mode": "Air",
  "total_package_count": 3,
  "total_package_weight": 3.4,
  "items": [
    {
      "item_id": "45a937f6-2724-40a4-8c9d-629f7c573ac9",
      "amount": 2
    }
  ]
}

###

### UPDATE SHIPMENT

PUT http://localhost:5000/api/shipments/090df922-046d-4379-bbd1-0ef696fecb83
Content-Type: application/json

{
  "order_id": "0415f598-6998-4340-8275-999dafb961e8",
  "order_date": "2023-11-19T14:12:33.807Z",
  "request_date": "2024-11-19T14:12:33.807Z",
  "shipment_date": "2024-11-19T14:12:33.807Z",
  "shipment_type": "I",
  "shipment_status": "Delivered",
  "notes": "geen notities",
  "carrier_code": "123",
  "carrier_description": "description",
  "service_code": "321",
  "payment_type": "Automatic",
  "transfer_mode": "Sea",
  "total_package_count": 3,
  "total_package_weight": 3.4,
  "items": [
    {
      "item_id": "45a937f6-2724-40a4-8c9d-629f7c573ac9",
      "amount": 5
    }
  ]
}

### DELETE SHIPMENT (change ID to the ID in your database)
DELETE http://localhost:5000/api/shipments/090df922-046d-4379-bbd1-0ef696fecb83
Content-Type: application/json

###

### GET ALL SHIPMENTS
GET http://localhost:5000/api/shipments
Content-Type: application/json

###

### GET SHIPMENT BY ID (change ID to existing ID in your database)
GET http://localhost:5000/api/shipments/090df922-046d-4379-bbd1-0ef696fecb83
Content-Type: application/json
