POST http://localhost:5000/api/Suppliers
Content-Type: application/json

{
  "code": "dit is een get item test",
  "name": "string",
  "reference": "123-ABCD",
  "contact_id": "936e76a5-37d5-4514-86b0-1caa13da5ac4",
  "address_id": "0ba16va7-0c7a-45de-9fe6-9054fb6df6a8"
}

###
PUT http://localhost:5000/api/Suppliers/3fe4cab3-3308-471e-8820-a8a126379ea4
Content-Type: application/json
  
 {
  "code": "VANAF NU IS HET EEN UPDATE TEST",
  "name": "string",
  "reference": "string",
  "contact_id": "f012a7c7-dfb0-4e54-9516-57bd51f9a7f8",
  "address_id": "016d60c2-a192-497a-b72c-49a1dedc3dab"
}

###

### GET ALL
GET http://localhost:5000/api/Suppliers
Content-Type: application/json

###

GET http://localhost:5000/api/Suppliers/9dd95911-0571-49b7-be44-cd18171569fe/Items
Content-Type: application/json

###

GET http://localhost:5000/api/Suppliers/a69d21c7-29b6-4fb3-9bc6-3ce1fe693ca3
Content-Type: application/json

###
DELETE http://localhost:5000/api/Suppliers/9dd95911-0571-49b7-be44-cd18171569fe
Content-Type: application/json
