POST http://localhost:5000/api/Suppliers
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiJ9.iRC-kafxS-kFeS894SbcIEFiAP-y8Nu9Ji0cz9K_h9c

{
  "code": "SUPPLIER_1",
  "name": "SUPPLIER 1",
  "reference": "123-ABCD",
  "contact_id": "56e02ed3-522d-45da-a80c-40ccaed4659d",
  "address_id": "457700a8-4d08-4d2d-94be-19465b28a0d1"
}

###
PUT http://localhost:5000/api/Suppliers/608aca13-9c94-4eb4-aa7c-eea50ce10f48
Content-Type: application/json
  
 {
  "code": "VANAF NU IS HET EEN UPDATE TEST",
  "name": "string",
  "reference": "string",
  "contact_id": "f012a7c7-dfb0-4e54-9516-57bd51f9a7f8",
  "address_id": "457700a8-4d08-4d2d-94be-19465b28a0d1"
}

###

### GET ALL
GET http://localhost:5000/api/Suppliers
Content-Type: application/json

###

GET http://localhost:5000/api/Suppliers/608aca13-9c94-4eb4-aa7c-eea50ce10f48/Items
Content-Type: application/json

###

GET http://localhost:5000/api/Suppliers/608aca13-9c94-4eb4-aa7c-eea50ce10f48
Content-Type: application/json

###
DELETE http://localhost:5000/api/Suppliers/608aca13-9c94-4eb4-aa7c-eea50ce10f48
Content-Type: application/json
