POST http://localhost:5000/api/Suppliers
Content-Type: application/json

{
  "code": "SUPPLIER_1",
  "name": "SUPPLIER 1",
  "reference": "123-ABCD",
  "contact_id": "e8483c51-1634-439d-958c-161bf9e7b61f",
  "address_id": "6d22935a-6c3f-418e-8bba-03b92cb38265"
}

###
PUT http://localhost:5000/api/Suppliers/608aca13-9c94-4eb4-aa7c-eea50ce10f48
Content-Type: application/json
  
 {
  "code": "VANAF NU IS HET EEN UPDATE TEST",
  "name": "string",
  "reference": "string",
  "contact_id": "f012a7c7-dfb0-4e54-9516-57bd51f9a7f8",
  "address_id": "016d60c2-a192-497a-b72c-49a1dedc3dab"
}

###

### GET ALL
GET http://localhost:5000/api/Suppliers
Content-Type: application/json

###

GET http://localhost:5000/api/Suppliers/608aca13-9c94-4eb4-aa7c-eea50ce10f48/Items
Content-Type: application/json

###

GET http://localhost:5000/api/Suppliers/608aca13-9c94-4eb4-aa7c-eea50ce10f48
Content-Type: application/json

###
DELETE http://localhost:5000/api/Suppliers/608aca13-9c94-4eb4-aa7c-eea50ce10f48
Content-Type: application/json
