POST http://localhost:5000/api/warehouses/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiJ9.iRC-kafxS-kFeS894SbcIEFiAP-y8Nu9Ji0cz9K_h9c

{
  "code": "WD_002",
  "name": "Sample Warehouse multi contact",
  "contact_ids": ["56e02ed3-522d-45da-a80c-40ccaed4659d"],
  "address_id": "457700a8-4d08-4d2d-94be-19465b28a0d1"
}
###

PUT http://localhost:5000/api/warehouses/5559d711-a141-46b3-b30b-4860f4d7879b
Content-Type: application/json

{
    "code": "WD_001 UPDATED",
    "name": "Test Company UPDATED",
  "contact_ids": [
    "3087768f-d44f-404b-a1b1-54a691ea94b7"
  ],
    "address_id": "59fdc093-b2d0-41fd-96b2-8f58030e53be"
}

### GET WAREHOUSES
GET http://localhost:5000/api/warehouses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiJ9.iRC-kafxS-kFeS894SbcIEFiAP-y8Nu9Ji0cz9K_h9c

###

### GET WAREHOUSE BY ID
GET http://localhost:5000/api/warehouses/eed6a18f-38ef-450a-bcc4-e0cbcfb82a57
Content-Type: application/json
###

### GET LOCATIONS FROM WAREHOUSE
GET http://localhost:5000/api/warehouses/eed6a18f-38ef-450a-bcc4-e0cbcfb82a57/locations
Content-Type: application/json
###

### GET DOCK and DOCK ITEMS FROM WAREHOUSE
GET http://localhost:5000/api/warehouses/4bb69c11-f4b0-439f-b584-62df6ebdfcc6/dock
Content-Type: application/json
###

### DELETE WAREHOUSE BY ID
DELETE http://localhost:5000/api/warehouses/eed6a18f-38ef-450a-bcc4-e0cbcfb82a57
Content-Type: application/json
###