POST http://localhost:5000/api/warehouses/
Content-Type: application/json

{
    "code": "TEST",
    "name": "Test Company",
    "contact_id": "8d2e7d61-e596-46e4-acd8-e85ef8805110",
    "address_id": "0ba16ba7-0c7a-45de-9fe6-9054fb6df6a8"
}
###
###

PUT http://localhost:5000/api/warehouses/8dbab3d8-34b4-4528-968b-74d8f94515a5
Content-Type: application/json

{
    "code": "Test update warehouse with id's",
    "name": "Test Company",
    "contact_id": "8d2e7d61-e596-46e4-acd8-e85ef8805110",
    "address_id": "0ba16ba7-0c7a-45de-9fe6-9054fb6df6a8"
}

###
GET  http://localhost:5000/api/warehouses
Content-Type: application/json

###

GET  http://localhost:5000/api/warehouses/8dbab3d8-34b4-4528-968b-74d8f94515a5
Content-Type: application/json

###

GET http://localhost:5000/api/Warehouses/7ef3414c-2bc5-4687-b551-b281e2781d4b/locations
Content-Type: application/json

###


### GET WAREHOUSES
GET http://localhost:5000/api/warehouses
Content-Type: application/json
###

### GET WAREHOUSE BY ID
GET http://localhost:5000/api/warehouses/6ae8144f-a5a4-49b0-a093-b0f30659f256
Content-Type: application/json
###

### GET LOCATIONS FROM WAREHOUSE
GET http://localhost:5000/api/warehouses/8dbab3d8-34b4-4528-968b-74d8f94515a5/locations
Content-Type: application/json
###

### DELETE WAREHOUSE BY ID
DELETE http://localhost:5000/api/warehouses/8dbab3d8-34b4-4528-968b-74d8f94515a5
Content-Type: application/json

###